name: Build Windows Version

on:
  push:
    branches:
      - main  # Adjust if needed
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest  # Run on Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"  # Updated to Python 3.13.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyQt6==6.8.1 Pandas==2.2.3 Matplotlib==3.10.0 Seaborn==0.13.2
          pip install -r requirements.txt  # Install additional dependencies

      #- name: Run tests (Optional)
        #run: pytest  # Ensure tests are set up

      - name: Build Windows Executable
        run: |
          pip install pyinstaller
          pyinstaller --noconfirm --onefile --windowed main.py  # Adjust main.py

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/main.exe  # Adjust based on your project
